@startuml
interface IPluginService {
    + GetList(page:int, pageSize:int, sortBy:string, order:SortDirection, search:string, cancellationToken:CancellationToken) : Task<PaginationList<PluginDTO>>
    + Add(data:PluginUploadData) : Task
    + Edit(dto:PluginDTO) : Task
    + Upgrade(data:PluginUpgradeData) : Task
    + Remove(id:Guid) : Task
    + StarPlugin(pluginId:Guid) : Task
    + UnstarPlugin(pluginId:Guid) : Task
    + IsPluginStarred(pluginId:string) : Task<bool>
}
@enduml
