@startuml
class PluginService {
    + PluginService(httpClient:HttpClient, getListEndpoint:string, addEndpoint:string, editEndpoint:string, upgradeEndpoint:string, removeEndpoint:string, starEndpoint:string, unstarEndpoint:string)
    + <<async>> Edit(dto:PluginDTO) : Task
    + <<async>> Upgrade(data:PluginUpgradeData) : Task
    + <<async>> GetList(page:int, pageSize:int, sortBy:string, order:SortDirection, search:string, cancellationToken:CancellationToken) : Task<PaginationList<PluginDTO>>
    + <<async>> Remove(id:Guid) : Task
    + <<async>> StarPlugin(pluginId:Guid) : Task
    + <<async>> UnstarPlugin(pluginId:Guid) : Task
    + <<async>> IsPluginStarred(pluginId:string) : Task<bool>
    + <<async>> Add(data:PluginUploadData) : Task
}
IPluginService <|-- PluginService
@enduml
