@startuml
class RequestLoggingMiddleware {
    + RequestLoggingMiddleware(next:RequestDelegate, logger:ILogger<RequestLoggingMiddleware>)
    + <<async>> InvokeAsync(context:HttpContext) : Task
}
@enduml
