@startuml
!include .\\Program.puml
!include .\\Controllers\AdminRequestAuthFilter.puml
!include .\\Controllers\AuthController.puml
!include .\\Controllers\GetUserInfoActionFilter.puml
!include .\\Controllers\NavMenuController.puml
!include .\\Controllers\PluginsController.puml
!include .\\Controllers\UsersController.puml
!include .\\Middleware\RequestLoggingMiddleware.puml
!include .\\Migrations\20250327135026_InitialCreate.puml
!include .\\Migrations\20250327135026_InitialCreate.Designer.puml
!include .\\Migrations\20250410114013_Update.puml
!include .\\Migrations\20250410114013_Update.Designer.puml
!include .\\Migrations\20250410114359_RemoveStarredInUser.puml
!include .\\Migrations\20250410114359_RemoveStarredInUser.Designer.puml
!include .\\Migrations\20250410142853_Timestamp.puml
!include .\\Migrations\20250410142853_Timestamp.Designer.puml
!include .\\Migrations\20250418030948_role.puml
!include .\\Migrations\20250418030948_role.Designer.puml
!include .\\Migrations\20250418031849_config.puml
!include .\\Migrations\20250418031849_config.Designer.puml
!include .\\Migrations\AppDbContextModelSnapshot.puml
!include .\\Repositories\IFileStorage.puml
!include .\\Repositories\IPluginRepository.puml
!include .\\Repositories\IRepository.puml
!include .\\Repositories\IUserRepository.puml
!include .\\Repositories\LocalFileStorage.puml
!include .\\Repositories\PluginRepository.puml
!include .\\Repositories\UserRepository.puml
!include .\\Services\AppDbContext.puml
!include .\\Services\AuthService.puml
!include .\\Services\BcryptPasswordHasher.puml
!include .\\Services\IAuthService.puml
!include .\\Services\IPasswordHasher.puml
!include .\\Services\IPluginService.puml
!include .\\Services\IUserService.puml
!include .\\Services\PluginService.puml
!include .\\Services\UserService.puml
!include .\\Models\DTO\UpgradePluginRequest.puml
!include .\\Models\DTO\UploadPluginRequest.puml
!include .\\Models\DTOMapper\IDTOMapper.puml
!include .\\Models\DTOMapper\PluginDTOMapper.puml
!include .\\Models\DTOMapper\UserDTOMapper.puml
!include .\\Models\Entities\Config.puml
!include .\\Models\Entities\ITimestampedEntity.puml
!include .\\Models\Entities\Plugin.puml
!include .\\Models\Entities\User.puml
!include .\\Models\Entities\User_Plugin.puml
!include .\\Services\ServerPluginManagement\ActionDescriptorChangeProvider.puml
!include .\\Services\ServerPluginManagement\DynamicPluginManager.puml
!include .\\Services\ServerPluginManagement\DynamicRouterTransformer.puml
!include .\\Services\ServerPluginManagement\DynamicServiceProvider.puml
@enduml
