@startuml
!include Config.puml
!include HashController.puml
!include HashRequest.puml
!include HashResponse.puml
!include HashService.puml
HashController "1" -- "1" HashService : "use"
HashController  --  HashRequest : "use"
HashController  --  HashResponse : "use"
@enduml