<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\SoftwareDesignProject.Client\SoftwareDesignProject.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.*" />
  </ItemGroup>


  <ItemGroup>
    <Content Update="Root\plugins\RazorClassLibrary_test.dll">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>


  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\plugins\RazorClassLibrary_test.dll" />
  </ItemGroup>


  <ItemGroup>
    <Reference Include="ControllerPluginTemplate">
      <HintPath>..\..\ControllerPluginTemplate\bin\Debug\net9.0\ControllerPluginTemplate.dll</HintPath>
    </Reference>
    <Reference Include="PluginTemplate">
      <HintPath>..\..\PluginTemplate\bin\Debug\net8.0\PluginTemplate.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>