<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\DTO\DTO.csproj" />
		<ProjectReference Include="..\SoftwareDesignProject.Client\SoftwareDesignProject.Client.csproj" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Dapper" Version="2.1.66" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.7.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.7.0" />
	</ItemGroup>


	<ItemGroup>
		<Content Update="Root\plugins\RazorClassLibrary_test.dll">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>


	<ItemGroup>
		<_ContentIncludedByDefault Remove="wwwroot\plugins\RazorClassLibrary_test.dll" />
	</ItemGroup>


	<ItemGroup>
		<Reference Include="BackendPluginTemplate">
			<HintPath>..\..\BackendPluginTemplate\bin\Debug\net9.0\BackendPluginTemplate.dll</HintPath>
		</Reference>
		<Reference Include="ClientPluginTemplate">
		  <HintPath>..\..\ClientPluginTemplate\bin\Debug\net8.0\ClientPluginTemplate.dll</HintPath>
		</Reference>
	</ItemGroup>


	<ItemGroup>
	  <Folder Include="Root\BackendPlugins\" />
	  <Folder Include="Root\ClientPlugins\" />
	</ItemGroup>

</Project>