@startuml
!include ./Services/IAuthService.puml
!include ./Services/AuthService.puml
!include ./Services/IUserService.puml
!include ./Services/UserService.puml
class SignInDialog {
    -IAuthService AuthService   
}

class SignUpDialog {
    -IAuthService AuthService
}

class UpgradeDialog {
    -IAuthService AuthService
}
SignInDialog "1" -- "1" IAuthService : "use"
SignUpDialog "1" -- "1" IAuthService : "use"
UpgradeDialog "1" -- "1" IUserService : "use"
@enduml