@startuml
class SignInDialog {
    -IAuthService AuthService   
}

class SignUpDialog {
    -IAuthService AuthService
}

class UpgradeDialog {
    -IAuthService AuthService
}

interface IAuthService {
    +SignIn(username: string, password: string): Task<bool>
    +SignUp(username: string, password: string): Task<bool>
    +Upgrade(): Task<bool>
}

class AuthService {
    + <<async>> SignIn(username: string, password: string): Task<bool>
    + <<async>> SignUp(username: string, password: string): Task<bool>
    + <<async>> Upgrade(): Task<bool>
}

IAuthService <|-- AuthService

SignInDialog "1" -- "1" IAuthService : "use"
SignUpDialog "1" -- "1" IAuthService : "use"
UpgradeDialog "1" -- "1" IAuthService : "use"
@enduml