version: '3.8'
services:
  DevToolsDB:
    image: postgres:latest
    container_name: devutils_postgres_db
    restart: always
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: devutils
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
