@startuml
class FormatChecker {
    + IsValidEmail(email:string) : bool
    + IsValidUsername(username:string) : bool
    + IsValidPassword(password:string) : bool
    + IsValidPluginName(name:string) : bool
    + IsValidPluginCategory(category:string) : bool
    + IsValidPluginDescription(description:string) : bool
}
IFormatChecker <|-- FormatChecker
@enduml
