@startuml
class HashController {
    + HashController(sp:IDynamicServiceProvider)
    + Hash(request:HashRequest) : IActionResult
    + Verify(request:VerifyRequest) : IActionResult
}
ControllerBase <|-- HashController
@enduml
