@startuml
class AdminRequestAuthFilter {
    + AdminRequestAuthFilter(userService:IUserService)
    + <<async>> OnActionExecutionAsync(context:ActionExecutingContext, next:ActionExecutionDelegate) : Task
}
IAsyncActionFilter <|-- AdminRequestAuthFilter
@enduml
