@startuml
class BCryptPasswordHasher {
    + HashPassword(password:string) : string
    + VerifyPassword(hashedPassword:string, providedPassword:string) : bool
}
IPasswordHasher <|-- BCryptPasswordHasher
@enduml
