@startuml
class DynamicPluginManager {
    + DynamicPluginManager(partManager:ApplicationPartManager, serviceProvider:IServiceProvider, changeProvider:IActionDescriptorChangeProvider, logger:ILogger<DynamicPluginManager>, fileStorage:IFileStorage)
    + <<async>> LoadAllAssemblies() : Task
    + CheckLoadedPlugin(uid:string) : bool
    + GetServiceProvider() : IServiceProvider
    + GetControllers(pluginId:string) : List<Type>
    + GetValidControllers(pluginId:string, controllerName:string) : List<Type>
    + <<async>> StartAsync(cancellationToken:CancellationToken) : Task
    + StopAsync(cancellationToken:CancellationToken) : Task
}
IHostedService <|-- DynamicPluginManager
@enduml
