###
POST http://localhost:5037/api/plugin/b33c175c-94a9-4d92-b6f8-b56c6ad450b3/hash/Verify
Content-Type: application/json

{
  "value": "hello",
  "hashed": "$2a$10$a5Pr3EUAU8LKqPY6vNHQROLa/v9meSfS3rCd4lFOh8umfbvAKk9Pi"
}

###


###
GET http://localhost:5037/api/load
Accept: application/json

###
POST http://localhost:5037/api/plugin/b33c175c-94a9-4d92-b6f8-b56c6ad450b3/hash/hash
Content-Type: application/json

{
  "value": "hello",
  "salt": 10
}

###

POST http://localhost:5037/api/plugin/7c22a439-fe40-4935-934b-e93804484289/Encrypt/Encrypt
Content-Type: application/json

{
  "data": "hello",
  "key": "123"
}

### 
POST http://localhost:5037/api/plugin/7c22a439-fe40-4935-934b-e93804484289/Encrypt/Decrypt
Content-Type: application/json

{
  "data": "xMB9BMm4QXiXAAfTcMmm1A==",
  "key": "123"
}